// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID                   uuid.UUID      `json:"id"`
	JobNumber            string         `json:"job_number"`
	JobName              string         `json:"job_name"`
	ContractValue        sql.NullString `json:"contract_value"`
	Address              sql.NullString `json:"address"`
	ScrNumber            sql.NullString `json:"scr_number"`
	ContractCompleteDate sql.NullTime   `json:"contract_complete_date"`
	StartDate            sql.NullTime   `json:"start_date"`
	EndDate              sql.NullTime   `json:"end_date"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type JobItem struct {
	ID             uuid.UUID      `json:"id"`
	JobID          uuid.UUID      `json:"job_id"`
	ParentID       uuid.NullUUID  `json:"parent_id"`
	SortOrder      int32          `json:"sort_order"`
	ItemNumber     string         `json:"item_number"`
	Description    string         `json:"description"`
	ScheduledValue string         `json:"scheduled_value"`
	JobCostID      sql.NullString `json:"job_cost_id"`
	Budget         string         `json:"budget"`
	Qty            string         `json:"qty"`
	Unit           sql.NullString `json:"unit"`
	UnitPrice      string         `json:"unit_price"`
}

type PayApplication struct {
	ID              uuid.UUID    `json:"id"`
	JobItemID       uuid.UUID    `json:"job_item_id"`
	PayAppMonth     time.Time    `json:"pay_app_month"`
	Qty             string       `json:"qty"`
	StoredMaterials string       `json:"stored_materials"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}
