// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Job struct {
	ID                   uuid.UUID      `json:"id"`
	JobNumber            string         `json:"job_number"`
	JobName              string         `json:"job_name"`
	ContractValue        sql.NullString `json:"contract_value"`
	Address              sql.NullString `json:"address"`
	ScrNumber            sql.NullString `json:"scr_number"`
	ContractCompleteDate sql.NullTime   `json:"contract_complete_date"`
	StartDate            sql.NullTime   `json:"start_date"`
	EndDate              sql.NullTime   `json:"end_date"`
	CreatedAt            sql.NullTime   `json:"created_at"`
	UpdatedAt            sql.NullTime   `json:"updated_at"`
}

type JobCostLedger struct {
	ID              string         `json:"id"`
	Job             string         `json:"job"`
	Phase           sql.NullString `json:"phase"`
	Cat             sql.NullString `json:"cat"`
	TransactionType sql.NullString `json:"transaction_type"`
	TransactionDate sql.NullTime   `json:"transaction_date"`
	Amount          string         `json:"amount"`
	CreatedAt       sql.NullTime   `json:"created_at"`
}

type JobItem struct {
	ID              uuid.UUID      `json:"id"`
	JobID           uuid.UUID      `json:"job_id"`
	ParentID        uuid.NullUUID  `json:"parent_id"`
	SortOrder       int32          `json:"sort_order"`
	ItemNumber      string         `json:"item_number"`
	Description     string         `json:"description"`
	ScheduledValue  string         `json:"scheduled_value"`
	JobCostID       sql.NullString `json:"job_cost_id"`
	Budget          string         `json:"budget"`
	Qty             string         `json:"qty"`
	Unit            sql.NullString `json:"unit"`
	UnitPrice       string         `json:"unit_price"`
	UpdatedAt       sql.NullTime   `json:"updated_at"`
	CostMethod      sql.NullString `json:"cost_method"`
	ProductionRate  sql.NullString `json:"production_rate"`
	ProductionUnits sql.NullString `json:"production_units"`
	ManHours        string         `json:"man_hours"`
	ProductionHours string         `json:"production_hours"`
	CrewDays        string         `json:"crew_days"`
	Plug            string         `json:"plug"`
	Labor           string         `json:"labor"`
	Equip           string         `json:"equip"`
	Misc            string         `json:"misc"`
	Material        string         `json:"material"`
	Sub             string         `json:"sub"`
	Trucking        string         `json:"trucking"`
	Indirect        string         `json:"indirect"`
	Bond            string         `json:"bond"`
	Overhead        string         `json:"overhead"`
	Profit          string         `json:"profit"`
}

type PayApplication struct {
	ID              uuid.UUID    `json:"id"`
	JobItemID       uuid.UUID    `json:"job_item_id"`
	PayAppMonth     time.Time    `json:"pay_app_month"`
	Qty             string       `json:"qty"`
	StoredMaterials string       `json:"stored_materials"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
}

type PayApplicationCumulative struct {
	JobItemID                uuid.UUID     `json:"job_item_id"`
	PayAppMonth              time.Time     `json:"pay_app_month"`
	JobID                    uuid.UUID     `json:"job_id"`
	ParentID                 uuid.NullUUID `json:"parent_id"`
	ThisMonthQty             string        `json:"this_month_qty"`
	StoredMaterials          string        `json:"stored_materials"`
	TotalQty                 string        `json:"total_qty"`
	UnitPrice                string        `json:"unit_price"`
	Budget                   string        `json:"budget"`
	CumulativeQty            string        `json:"cumulative_qty"`
	PreviousCumulativeQty    string        `json:"previous_cumulative_qty"`
	RemainingQty             string        `json:"remaining_qty"`
	PercentComplete          string        `json:"percent_complete"`
	ThisMonthAmount          string        `json:"this_month_amount"`
	CumulativeAmount         string        `json:"cumulative_amount"`
	PreviousCumulativeAmount string        `json:"previous_cumulative_amount"`
}
